#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.67/sit_3.67p2.tar.gz"
URL="https://sourceforge.net/projects/sitracker/files/stable/$VERSION"
dl $URL /usr/local/src

