#!/bin/sh -ex

DB_NAME=sitracker
DB_USER=sitracker
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/sitracker

# unpack
tar -zxf $SRC/sit_*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/sit-* $WEBROOT
rm $SRC/sit_*.tar.gz
chown -R root:root $WEBROOT

# create attachments and preconfigure database settings
ATTACHMENTS=$WEBROOT/attachments-$(mcookie)
mkdir -p $ATTACHMENTS
chown -R www-data:www-data $ATTACHMENTS

cat >$WEBROOT/config.inc.php<<EOF
<?php
\$CONFIG['db_hostname'] = 'localhost';
\$CONFIG['db_username'] = '$DB_USER';
\$CONFIG['db_password'] = '$DB_PASS';
\$CONFIG['db_database'] = '$DB_NAME';
\$CONFIG['attachment_fspath'] = '$ATTACHMENTS/';

// You may override variables configured in defaults.inc.php here

?>
EOF
chown www-data:www-data $WEBROOT/config.inc.php
chmod 440 $WEBROOT/config.inc.php

# configure apache
a2dissite 000-default
a2ensite sitracker
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/setup.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL $URL
$CURL $URL --data "action=checkinstallcomplete"
$CURL $URL --data "newpassword=$ADMIN_PASS&passwordagain=$ADMIN_PASS&email=$EMAIL&action=createadminuser"

rm -f /tmp/cookie

# set site name
$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO config VALUES ('application_name', 'TurnKey SiTracker');"

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

