#!/bin/bash -e
# regenerate sitracker secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/sitracker/config.inc.php

ATTACHMENTS=/var/www/sitracker/attachments-$(mcookie)
mv /var/www/sitracker/attachments-* $ATTACHMENTS
sed -i "s|attachment_fspath.*|attachment_fspath'] = '$ATTACHMENTS/';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|db_password.*|db_password'] = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=sitracker --pass="$PASSWORD"

